### ISSUE TITLE
Add option to prevent private rooms

### ISSUE THREAD

**Issue by mweibel** [candy-chat/candy#214]
See [mailinglist](https://groups.google.com/forum/#!topic/candy-chat/HkZj8wHLZeM)

We should discuss how to do it/whether we should do it.

**Comment by skarimi110** [comment]
How to implement this shit?

**Comment by mweibel** [comment]
Dear @skarimi110. I appreciate the time you put in your comment. This comment brings a lot of value and deserves a well thought answer by one of the contributors. I'd like to explain you how to implement this shit: 

```
$(github.document).on('shit', function doShits() {
  throw PleaseBeNiceOrIwillReportYouError("What the heck did you think when writing this question?");
});
```

I hope you appreciate the time I put into my comment.

**Comment by pstadler** [comment]
![](http://share.koeniglich.ch/macdrop/beard-slap.gif)
