### ISSUE TITLE
No UI shows after login

### ISSUE THREAD

**Issue by walidsynclio** [candy-chat/candy#221]
Hi,
I am trying get experiment a working chat client. I have cloned candy and make changed to examples/htaccess and examples/index.html.
when i hit the url in my browser I see login form.
entered jid and password. it logs in correctly, I can see in chrome developer console as well on the ejabberd server logs.
But after that I do not see any view, page is just grey.
If send ant chat from some other client it is received and show in chrome console but no ui. 
Is there anything else I have to do to get UI.
Thanks
Abul Walid

**Comment by poseroo** [comment]
hi i did everything what it said in the installation guide but candy doe not connect to my server.. what should i do?
