### ISSUE TITLE
Responsive Design

### ISSUE THREAD

**Issue by maennchen** [candy-chat/candy#222]
It would be nice to have a responsive design for Candy.

https://github.com/candy-chat/candy-plugins/issues/72

**Comment by DannyCork** [comment]
Responsive is a must !

**Comment by benlangfeld** [comment]
Do you have any code to contribute, @DannyCork?

**Comment by marclaporte** [comment]
Hi!

I am willing to "make it happen" with Bootstrap.

I'd like:
1- At least one volunteer for testing. Everyone in this thread should volunteer :-)
2- Confirmation from a project leader that the pull request will be accepted to be part of the next major stable version (conditional to quality of course)

The Bootstrap front-end framework is ideal to make an interface responsive:
https://en.wikipedia.org/wiki/Bootstrap_(front-end_framework)
And responsive is not just about small screens. It's also about huge (wall-sized) screens.

Bootstrap provides many benefits, one of which is easy access to theme generators and thousands of free and paid themes. But also "mobile-first" design and intensive testing with all browsers, etc. Many apps have moved to Bootstrap, like Joomla!, Moodle, phpMyFAQ, Tiki Wiki CMS Groupware, ClearOS, etc. and some have been built with it from the ground up. Ex.: Syncthing

The Bootstrap community is very active and has the expertise and energy to do a fantastic job in this area, and also to solve edge cases and browser bugs that a community like Candy would never want to go so deep in. To illustrate, please see the "Wall of browser bugs" http://getbootstrap.com/browser-bugs/

Some stats:

Most starred project on Github (double the stars of #2)
https://github.com/search?q=stars:%3E1&s=stars&type=Repositories

Over 700 have contributed source code:
https://www.openhub.net/p/bootstrap-from-twitter

13% of the top 1 million sites are using Bootstrap:
http://trends.builtwith.com/docinfo/Twitter-Bootstrap
And at least 6 million sites in all.

Beyond the Bootstrap code itself, the ecosystem is huge and diverse. Here is a "tour / help" lib which could be really cool as a helper for new users to Candy:
http://bootstraptour.com/

Over 300 other resources:
http://bootstraphero.com/the-big-badass-list-of-twitter-bootstrap-resources

Bootstrap 3.x is mature now, and 4.x is one the way:
https://twitter.com/mdo/status/630998241547436032

Best regards,

M ;-)

**Comment by humitos** [comment]
@marclaporte I can be a volunteer for testing with a Nexus 5 Android 6.0

**Comment by benlangfeld** [comment]
> Confirmation from a project leader that the pull request will be accepted to be part of the next major stable version (conditional to quality of course)

Assuming that the implementation is of a high standard, I would have no problem making this move. Thanks for volunteering, @marclaporte.

**Comment by DannyCork** [comment]
Ive a device lab write 8 tablets and phones. I'd like to offer my services also. 

let the fun begin!

**Comment by marclaporte** [comment]
Super!

FYI: Candy and Jitsi Meet are both components part of Openfire Meetings, which we want responsive:
https://community.igniterealtime.org/blogs/ignite/2015/02/14/realtime-collaboration-with-openfire-meetings

So we will convert them both to Bootstrap and contribute to each project. Here is the issue tracking for converting Jitsi Meet to Bootstrap:
https://github.com/jitsi/jitsi-meet/issues/335

Best regards,

M ;-)

**Comment by marclaporte** [comment]
Hi again!

Sorry for the delay. We got caught up on a big project, which was launched yesterday, so we now get back to this.

Thanks!

**Comment by marclaporte** [comment]
Any day now, a commit and a demo site will appear :-)

**Comment by marclaporte** [comment]
So we can close this ticket with "coming in 2.2" ?

Thanks!

**Comment by benlangfeld** [comment]
Indeed

**Comment by joudinet** [comment]
Hi,
I've just tested your new responsive design (well not so new anymore but it's been a long time since I tested candy-chat) on both an android 6+ phone (a oneplus 3 model) and an iPhone 6s.
On the android phone (chrome), it works really well. Thank you. I see only a small glitch with the new hamburger button. It sticks on the top-right even it there is other elements here than the candy's div, but that's quite easy to fix for me.
However, on the iPhone (Safari), it's still very hard to use candy-chat because when you click on the input field to send a message, it zooms in in this field (so you can't see the previous messages), and it does not zoom out afterwards. So basically, you have to zoom out after every sent message to continue to follow a conversation :-(
Any idea how to force iOS/Safari to behave (like android/chrome)?
