### ISSUE TITLE
Private chats with other jabber clients

### ISSUE THREAD

**Issue by oleid** [candy-chat/candy#227]
Hello *!

I've just upgraded from candy-1.0.9 to git head and realized that when I send a message from e.g. pidgin to a user which is online via candy, the messages get lost and no tab is opened inside candy for this conversation.

On the other hand, I can now successfully initiate private messages to users online with e.g. pidgin. This didn't work with the old version. Yet, pidgin displays

 room@conference.myserver.de/localUsername   as username, where as the username should be localUsername@myserver.de -- maybe this is somehow connected to the issue at hand.

Would you guide me in finding the problem?

Best,

Olaf

**Comment by benlangfeld** [comment]
I believe this should all be wrap up, so I'll close this for now. If there's anything left to be done, someone please do shout :)
