### ISSUE TITLE
Nothing appears after authenticating

### ISSUE THREAD

**Issue by ghost** [candy-chat/candy#230]
Hello. I've authenticated to the xmpp server and in the login dialog it does say I connected and then all I get is a solid #444444 background color. Nothing else shows up. I am using the latest version of Candy.

No errors appear in the console.

**Comment by shahidkarimi** [comment]
How to give array of rooms?

**Comment by mweibel** [comment]
Using a javascript array, see http://candy-chat.github.io/candy/#configuration "autojoin"
