### ISSUE TITLE
OTR - Messaging?

### ISSUE THREAD

**Issue by cmllr** [candy-chat/candy#238]
Is there anything planned to allow messaging using "Off the record"?

**Comment by Dafvid** [comment]
How about https://github.com/arlolra/otr?

It would be a good plugin.

**Comment by benlangfeld** [comment]
@Dafvid Contributions welcome :)

**Comment by Dafvid** [comment]
I'm looking at it right now but don't hold your breath =) All pointers appreciated. I have Prosody running and OTR added in Pidgin so I'm pretty set for testing.
