### ISSUE TITLE
Can't see user join after kick

### ISSUE THREAD

**Issue by shizend** [candy-chat/candy#240]
When user who have been kicked, join to room again and another user can't see him.

**Comment by olivierobert** [comment]
I could reproduce the issue explained by @shizend . So the solution provided by @Hypher is the correct one for now. So checking if `user` exists before calling the below method:

```
$(Candy).triggerHandler("candy:core.presence.room", {
    roomJid: roomJid,
    roomName: room.getName(),
    user: user,
    action: action,
    currentUser: currentUser
});
```
