### ISSUE TITLE
Global Roster

### ISSUE THREAD

**Issue by melissanoelle** [candy-chat/candy#256]
It looks as if Candy.Core.Action.Jabber.Roster() doesn't reach out for the global roster, nor can I find any place that would already be easily available to get it to return this to me... I am working on a global roster plugin, but it looks as if I'd need to include the strophe plugin for roster to the grunt file (which also needs to be updated) and then add a function to run it (provided something like `fetchGlobalRoster: true` is set in the `Candy.init()` function) and then perhaps add a trigger event for each incoming stanza?

Should I leave it at that and allow the plugin I'm working on to handle creating a lobby-like roster, or should I continue that in Candy core?

Or, can you think of a way to accomplish this without altering Candy's core?

**Comment by benlangfeld** [comment]
A global roster is now included in Candy core.
