### ISSUE TITLE
Feature request: Add "# Unread messages" for MUC

### ISSUE THREAD

**Issue by oxivanisher** [candy-chat/candy#270]
Feature request:

Add "# Unread messages" in page title not only for Private messages but for all the channels combined. This should be a configuration option to not kill chats on big sites.

**Comment by Sudrien** [comment]
[addressed in #349, updateWindowOnAllMessages option]

**Comment by benlangfeld** [comment]
Closing this on the expectation that #349 satisfied the request. Please let me know if I'm wrong.
