### ISSUE TITLE
unread count for chats

### ISSUE THREAD

**Issue by indeyets** [candy-chat/candy#327]
Right now, unread counters are updated only for private chats. Is it possible to (conditionally) enable them for regular chats as well?

Configuration option would do.

**Comment by Sudrien** [comment]
I've been looking into this for my own install. 

On both master, there currently no option. 

<pre>if (self.Chat.rooms[roomJid].type === "chat") {
    self.Window.increaseUnreadMessages();
}</pre>

Commenting out the if condition line and the following curly brace is a temporary hack.
On dev, there is a similar check, albeit in a different place. Adding a condition would be trivial

<pre>if (self.Chat.rooms[roomJid].type === "chat" || Candy.View.getOptions().updateWindowOnAllMessages) {
    self.Window.increaseUnreadMessages();
}</pre>

Caveat being, if the chat is in an iframe, this still has no effect on the parent window.

I'll be looking for a non-hack way to add checks for parent documents.
