### ISSUE TITLE
demo broken

### ISSUE THREAD

**Issue by daurnimator** [candy-chat/candy#330]
Trying to use https://candy-chat.github.io/candy/#demo on recent chrome:

> Mixed Content: The page at 'https://candy-chat.github.io/candy/#demo' was loaded over HTTPS, but requested an insecure script 'http://ajax.googleapis.com/ajax/libs/jquery/1.7.0/jquery.min.js'. This request has been blocked; the content must be served over HTTPS.

Use schema-less url to fix
Fix location: https://github.com/candy-chat/candy/blob/gh-pages/index.html#L11

**Comment by mweibel** [comment]
Thanks. Demo won't work anyway as I don't have a SSL cert on the demo host..

**Comment by daurnimator** [comment]
damn. Can you get a cert? startssl has them for free.
Otherwise you could try using either ngrok or cloudflare, which will make the requests over https.

**Comment by pstadler** [comment]
@mweibel we should fix this somehow.

**Comment by mweibel** [comment]
Fixed finally.. :)

**Comment by daurnimator** [comment]
great :)

**Comment by pstadler** [comment]
:tophat:
