### ISSUE TITLE
Choking on jabber:iq:version?

### ISSUE THREAD

**Issue by Sudrien** [candy-chat/candy#331]
I'm using Openfire & punjab. 

Several messages in I'm getting a js dump, which seems to be triggered by the message

    RECV: <body xmlns='http://jabber.org/protocol/httpbind'><iq xmlns='jabber:client' to='sudrien@example.net/Candy' type='get' id='54-15' from='manager.example.net'><query xmlns='jabber:iq:version'/></iq></body>

Which calls on Strophe.escapeNode

It only seems to show up on a user I created; not for automatically generated users. 

The only relevant place I'm seeing this is in Strophe itself -

    /** Function: addFeature
     *
     * Parameters:
     *   (String) var_name - feature name (like jabber:iq:version)
     *
     * Returns:
     *   boolean
     */

Is this a call I should be making in my setup? Because it looks like - according to http://xmpp.org/extensions/xep-0092.html - it should be replying with Candy's version somehow.

**Comment by mweibel** [comment]
Hi,

Could you show the exception with the stacktrace?

**Comment by Sudrien** [comment]
I've switched to prosody, I have not seen the error since... and I was pretty aggressive in clearing out the previous stack - yeah, more that a little impatient. 

What I can say is:
The message was recieved from Openfire 3.9.3 (on openjdk 7) + punjab on Ubuntu 12.04LTS.
The room allowed both anonymous access & logins.

    from='manager.example.net'

At no point did I specify anything having to do with the word 'manager', though I can't say if that showed up anywhere else with confidence.

If this is not enough to work with, my apologies.

**Comment by mweibel** [comment]
Nah, it's not :) closing this then
