### ISSUE TITLE
Openshift Quickstart?

### ISSUE THREAD

**Issue by chrisvella** [candy-chat/candy#337]
I noticed your candy demo is being hosted on openshift. Is a quickstart or some instructions available to do this?

Thanks for the amazing work.

**Comment by mweibel** [comment]
Hi Chris,

I'm afraid it's not. I tried openshift at the very beginning but then didn't use it anymore (no specific reason though). 
There is still a repo online though, maybe you can use it as an inspiration: https://github.com/mweibel/candy-node/commits/openshift

Best,
Michael

**Comment by chrisvella** [comment]
Thanks for the clarification Michael.


Chris
