### ISSUE TITLE
Maybe Issue

### ISSUE THREAD

**Issue by eossipov** [candy-chat/candy#345]
I use the virus scanner "herd protect" (great app, highly recommend it.)
It marked this app as a virus, or as having one. I thought you might like to submit it to these folks, as they seem to be growing as the definitive source. I'm about 85% sure I marked it a false positive,

here's the URL: http://www.herdprotect.com/
Are you a software publisher and would like to find out how to get on the 'trusted list'? Connect with us at trust@herdProtect.com.
and here is the email to their 'trust' list.

**Comment by mweibel** [comment]
I think the correct answer to this is: Go fuck yourself
