### ISSUE TITLE
IE9 - SCRIPT16385: Not Implemented

### ISSUE THREAD

**Issue by tylermauthe** [candy-chat/candy#356]
I am doing some cross-browser testing of the Candy.js implementation I'm working on and finding that it doesn't work with IE9.

If you open the Developer Tools Console, there is a mysterious "SCRIPT16385: Not Implemented" error shown.

At first I thought it was a modification I had made somewhere, but this happens for me on the demo on the GitHub site.

Any assistance with this issue would be greatly appreciated!

**Comment by mweibel** [comment]
Weird. Which version of candy do you use?

**Comment by tylermauthe** [comment]
I'm using the latest (1.7.1) and jQuery 1.11.1

However, I see the same behaviour on the Candy Demo page: http://candy-chat.github.io/candy/#demo

**Comment by tylermauthe** [comment]
Here is the SauceLabs log of the issue: https://saucelabs.com/tests/54e281557cc64cf9a62539f8801ff698

**Comment by mweibel** [comment]
seems it has something to do with the native audio stuff, feature detection probably not done correctly. 
Could you send me line number for a candy.bundle.js (including candy.bundle.js instead of candy.min.js)?

**Comment by tylermauthe** [comment]
Don't you just love IE?

The line number in the unminified file is:
`candy.bundle.js, line 3405 character 17`

And here's the updated video it came from:
https://saucelabs.com/tests/e90774d1d90f427596730c6f4826e8e5

Looks like you're correct, that section is referring to audio. Perhaps some feature detection code could be borrowed from Modernizr:
https://github.com/Modernizr/Modernizr/blob/214f02af7b6e030de5d6422133c36975f74929bb/feature-detects/audio.js#L27-L46

It looks like the major difference (apart from formatting) is to wrap the test in a try/catch.

**Comment by Sudrien** [comment]
#351 has been updated.

**Comment by tylermauthe** [comment]
Fixed by #351
