### ISSUE TITLE
node-xmpp

### ISSUE THREAD

**Issue by sonnyp** [candy-chat/candy#358]
Hey, we've just setup our candy webchat,
http://node-xmpp.org/webchat/ 

I wondered if you'd be interested in moving to node-xmpp-client and if there something I could do to help on node-xmpp.

node-xmpp@muc.node-xmpp.org

**Comment by benlangfeld** [comment]
What would be the advantages of using node-xmpp-client over Strophe? Or over Stanza.IO for that matter?

**Comment by sonnyp** [comment]
Yeah you'd probably be better of with stanza.io or xmpp-ftw.

**Comment by benlangfeld** [comment]
If those libraries are "better" for Candy, for what would node-xmpp-client be better? I'm not a fan of Node.js generally, but in the browser I'm pretty much only familiar with Strophe. I'm genuinely curious how your library fits in.

**Comment by sonnyp** [comment]
@benlangfeld node-xmpp is lower level. Both XMPP-FTW and Stanza.IO use it.

**Comment by benlangfeld** [comment]
Ah, thanks for clearing that up @sonnyp. I've been considering Stanza.IO for a while.

Cc @melissanoelle

**Comment by sonnyp** [comment]
@benlangfeld XMPP-FTW is also a great piece of software but requires an additional server side component which might not makes sense for candy. There is an issue open for Stanza.io to use node-xmpp-client https://github.com/otalk/stanza.io/issues/82

**Comment by mweibel** [comment]
xmpp-ftw is not an option for Candy, as you say correctly. But I don't want to switch the library unless Strophe would be not supported anymore. I don't see the advantage and just see the amount of work required to do it.

This has nothing to do with the respective projects though, I like them obviously and if I'd do Candy from scratch I'd most likely would chose one of those libraries :+1: 

Thanks for using Candy as the webchat btw :)
