### ISSUE TITLE
Add chat state notifications support

### ISSUE THREAD

**Issue by linkmauve** [candy-chat/candy#359]
As defined here: http://xmpp.org/extensions/xep-0085.html

Some implementation ideas:
- In MUC it could be implemented with the nick sending the notifications changing its color.
- Some commonly used colors are green for composing, blue for paused and gray for inactive.
- In private as a message somewhere like “… is composing a message”, “… stopped composing a message” and “… is inactive”.
- You need to send chatstates if you want to receive them, except in MUC, but maybe add an option to disable it.

**Comment by benlangfeld** [comment]
Is this a feature request?

**Comment by linkmauve** [comment]
Yes, was there a better place to do it? Or a way to tag it correctly as one?

**Comment by benlangfeld** [comment]
Nope, just clarifying.

@melissanoelle might be interested in this since she's worked on these features in a plugin.

**Comment by mweibel** [comment]
Could also be an option as a plugin. It should be possible to disable this anyway, and I think the better option would be to add it as a plugin.

**Comment by mweibel** [comment]
Ah, btw. 
https://github.com/candy-chat/candy-plugins/tree/master/typingnotifications

Closing this then.
