### ISSUE TITLE
Hide joining and leaving notifications

### ISSUE THREAD

**Issue by arnaud** [candy-chat/candy#364]
Hi,

Is it possible to prevent joining and leaving notifications from displaying at all?
I'd like them not to be appended to my chatroom.
It can be very spamy and messes up with the actual discussions of the chatroom.

Thanks guys~

**Comment by mweibel** [comment]
see https://github.com/candy-chat/candy/blob/master/src/view/pane.js#L496

You can either set the cookie by default or set `Candy.View.Pane.Chat.infoMessage = function() {}` in your html file.

**Comment by arnaud** [comment]
Kudos. It worked.
Thank you~
