### ISSUE TITLE
URL autolinker

### ISSUE THREAD

**Issue by arnaud** [candy-chat/candy#377]
When posting an URL with a special character in it, the URL autolinking is broken and assumes the URL ends before the special character.
Example:

    http://www.consortium-horizon.com/nos-autres-p'tits-jeux/(fractured)-faire-piou-piou-avec-des-gros-vaisseaux/

will link to:

    http://www.consortium-horizon.com/nos-autres-p

Special characters include the following (not an extended list):

    '    (   )

**Comment by Sudrien** [comment]
@arnaud - looking for a full list at the moment - perchance are you on Chrome or Opera (or somthing else Webkit based)?

**Comment by arnaud** [comment]
I'm on both Firefox and Chrome, yes. Why?

**Comment by Sudrien** [comment]
One of my users just reported the parenthesis issue to me independently. I'm wondering if Webkit _not_ urlencoding links before copying them to the clipboard is a recent thing.

Not to self: https://mathiasbynens.be/demo/url-regex is pretty comprehensive, see if there isn't somthing shorter with good coverage

**Comment by Sudrien** [comment]
[Fixed in #380]

**Comment by arnaud** [comment]
Thanks!
