### ISSUE TITLE
IE11: XHTML Colors not working

### ISSUE THREAD

**Issue by Drakemor** [candy-chat/candy#379]
When using Candy with XTHML Colors, clients logged on IE don't see colors on chat (other browsers are working well). 

I noticed that in debug log the RECV from message is missing the <addr>xmlns='http://www.w3.org/1999/xhtml' </addr> argument from 2nd body element.

**Comment by mweibel** [comment]
Do you see an error in the browser console?
Are the messages which aren't rendered properly sent from Candy or from other XMPP clients?

**Comment by Drakemor** [comment]
Unfortunatelly no errors to give clues whats wrong.

Here is example RECV:
`RECV: <body xmlns='http://jabber.org/protocol/httpbind'><message type='groupchat' xmlns='jabber:client' to='8ef0de6d@eroczat.tk/8ef0de6d' id='34' from='foyer@chat.eroczat.tk/MistrzGry'><body>test</body><html xmlns='http://jabber.org/protocol/xhtml-im'><body><span style='color: rgb(73, 26, 255);'>test</span></body></html><x xmlns='jabber:x:event'><composing/></x></message></body>`

And the init of candy
`		$(document).ready(function() {
			var options={
				'core': { debug: true, autojoin: ['foyer@chat.eroczat.tk'] },
				'view': { assets: '../res/', enableXHTML: true }
			};
			Candy.init('http-bind/', options);
CandyShop.ColorsXhtml.init([
		'#B3B3B3', '#808080', '#3D3D3D', '#000000',
		'#FF1A1A', '#800000', '#510000', '#340B0B', 
		'#FFA21A', '#804D00', '#513100', '#34240B', 
		'#FFE11A', '#806F00', '#514600', '#3F3800', 
		'#95FF1A', '#448000', '#2B5100', '#213F00', 
		'#1AFF76', '#008033', '#005120', '#0B341B', 
		'#1AFEFF', '#008080', '#005151', '#0B3434', 
		'#1A76FF', '#003380', '#002051', '#0B1B34', 
		'#491AFF', '#1A0080', '#100051', '#130B34', 
		'#CF1AFF', '#660080', '#410051', '#2B0B34', 
		'#FF1AA2', '#80004D', '#510031', '#340B24']);`

The colors are working fine on chrome and firefox. And I'm not the only user that doesn't see them on IE. 

Am I'm doing something wrong?

**Comment by Drakemor** [comment]
Ok I know whats the deal - I had installed the MASTER branch.
In DEV branch colors work nice.

**Comment by Sudrien** [comment]
[fixed in #340]
