### ISSUE TITLE
Candy not working with Ejabberd 15.03 websockets

### ISSUE THREAD

**Issue by barhorn** [candy-chat/candy#384]
I am attempting to connect to a new Ejabberd 15.03 server, which supports websockets.  I downloaded the latest version of Candy (both the 1.7.1 version from the download link on the main page as well as the latest master branch from github) and tried to get the included example to work.  I changed the connection URL from the default to my webservice URL (ex: ws://<hostname>:5280/xmpp) then loaded it in my page (I did try a number of other config options over the course of testing, all to no avail).  After typing in my JID and password I can see in Chrome's network debug tools that the web socket is connecting and it is going through all the (apparent) correct sequences, but at the end I just get a "Disconnected" message and it shows the login prompt again.

Independently, I created a test js file using strophe and connected to the same server.  I see the same websocket streams, and when I ping the logged in user from another location (ex: Digby that is connected to another account on the same server) I can see the correct presence, message, etc information coming back to me in the console.  So it *looks* like the server is configured correctly (at least for this test), but I can't get Candy to actually authenticate.  

If you would like me to set you up an account on that server so you can run your own test, let me know.

**Comment by benlangfeld** [comment]
This is a bug that has been fixed on ejabberd master. Build from there or wait for the next ejabberd release.
