### ISSUE TITLE
Uncaught TypeError: Cannot read property 'scrollTop' of undefined

### ISSUE THREAD

**Issue by shahidkarimi** [candy-chat/candy#390]
I am having this error on all browsers. 

Uncaught TypeError: Cannot read property 'scrollTop' of undefined

The error seems to be in the candy.bundle.js

 tabClick: function(e) { 
            // remember scroll position of current room
            var currentRoomJid = Candy.View.getCurrent().roomJid;
            self.Chat.rooms[currentRoomJid].scrollPosition = self.Room.getPane(currentRoomJid, ".message-pane-wrapper").scrollTop();
            self.Room.show($(this).attr("data-roomjid"));
            e.preventDefault();
        },

**Comment by mweibel** [comment]
Which version of jQuery do you use?

**Comment by pavelsc** [comment]
I have 2.1.3 and the same issue. It occurs when you don't use autojoin option and receive message, e.g. you haven't had opened chats yet. I think the solution is:
```
tabClick: function(e) {
	// remember scroll position of current room
	var currentRoomJid = Candy.View.getCurrent().roomJid;
	if(currentRoomJid){
		self.Chat.rooms[currentRoomJid].scrollPosition = self.Room.getPane(currentRoomJid, '.message-pane-wrapper').scrollTop();

		self.Room.show($(this).attr('data-roomjid'));
		e.preventDefault();
	}
},
```
