### ISSUE TITLE
Candy chat does not work over HTTPS

### ISSUE THREAD

**Issue by shahidkarimi** [candy-chat/candy#393]
How candy is configured so that it works over https. Before applying SSL to my website everything was working fine. Now things weird up when SSL installed for my website.

Getting these errors:
POST https://mywebiste.com:7443/http-bind/ net::ERR_INSECURE_RESPONSE

**Comment by benlangfeld** [comment]
Did you configure your XMPP server for SSL? This is most likely an issue for your XMPP server provider, and almost certainly not a Candy bug. We have a mailing list for usage questions: http://groups.google.com/group/candy-chat.
