### ISSUE TITLE
How to get user jid while printing the chat message divs?

### ISSUE THREAD

**Issue by skarimi110** [candy-chat/candy#395]
How can I detect "ME" current user here:
 item: '<li class="{{agha_fokar}}"><small>{{time}}</small><div><span c.....

**Comment by benlangfeld** [comment]
`Candy.Core.getUser().getJID()`. We have a mailing list for questions; please use it.

**Comment by skarimi110** [comment]
No, not this. This will return the current user jid. I want the user id from messages. For formatting my messages in different font
