### ISSUE TITLE
Why I am receiving this response

### ISSUE THREAD

**Issue by skarimi110** [candy-chat/candy#398]
[Connection] Connecting
candy.min.js:1 SENT: <body rid='2628092928' xmlns='http://jabber.org/protocol/httpbind' to='hp-pc' xml:lang='en' wait='60' hold='1' content='text/xml; charset=utf-8' ver='1.6' xmpp:version='1.0' xmlns:xmpp='urn:xmpp:xbosh'/>
candy.min.js:1 RECV: <body xmlns='http://jabber.org/protocol/httpbind' xmlns:stream='http://etherx.jabber.org/streams' from='bizbeakn.com' authid='7dd87e4f' sid='7dd87e4f' secure='true' requests='2' inactivity='30' polling='5' wait='60' hold='1' ack='2628092928' maxpause='300' ver='1.6'><stream:features><mechanisms xmlns='urn:ietf:params:xml:ns:xmpp-sasl'><mechanism>DIGEST-MD5</mechanism><mechanism>PLAIN</mechanism><mechanism>ANONYMOUS</mechanism><mechanism>CRAM-MD5</mechanism></mechanisms><register xmlns='http://jabber.org/features/iq-register'/><bind xmlns='urn:ietf:params:xml:ns:xmpp-bind'/><session xmlns='urn:ietf:params:xml:ns:xmpp-session'><optional/></session></stream:features></body>
candy.min.js:1 SENT: <body rid='2628092929' xmlns='http://jabber.org/protocol/httpbind' sid='7dd87e4f'><auth xmlns='urn:ietf:params:xml:ns:xmpp-sasl' mechanism='DIGEST-MD5'/></body>
candy.min.js:1 RECV: <body xmlns='http://jabber.org/protocol/httpbind'><challenge xmlns='urn:ietf:params:xml:ns:xmpp-sasl'>cmVhbG09ImJpemJlYWtuLmNvbSIsbm9uY2U9Ik1jMDUycWd6dnhEVGZDYzhVeGhoWXE0TitUaHU5Qy9HQzVQOVZvQkgiLHFvcD0iYXV0aCIsY2hhcnNldD11dGYtOCxhbGdvcml0aG09bWQ1LXNlc3M=</challenge></body>
candy.min.js:1 SENT: <body rid='2628092930' xmlns='http://jabber.org/protocol/httpbind' sid='7dd87e4f'><response xmlns='urn:ietf:params:xml:ns:xmpp-sasl'>Y2hhcnNldD11dGYtOCx1c2VybmFtZT0ic2hhaGlkIixyZWFsbT0iYml6YmVha24uY29tIixub25jZT0iTWMwNTJxZ3p2eERUZkNjOFV4aGhZcTROK1RodTlDL0dDNVA5Vm9CSCIsbmM9MDAwMDAwMDEsY25vbmNlPSIzMzA4YzY0YTM2YTAzYzJmOTlkZWQyY2M5YmRmMGRkYSIsZGlnZXN0LXVyaT0ieG1wcC9ocC1wYyIscmVzcG9uc2U9MmJmNjdhMGI3MGMwMDJjNGZmODg1ZjQ4OTdiZGFjZWMscW9wPWF1dGg=</response></body>
candy.min.js:1 RECV: <body xmlns='http://jabber.org/protocol/httpbind'><failure xmlns='urn:ietf:params:xml:ns:xmpp-sasl'><not-authorized/></failure></body>
candy.min.js:1 [Connection] Authentication failed

**Comment by benlangfeld** [comment]
Mailing list or we block you.
