### ISSUE TITLE
Future of the candy project

### ISSUE THREAD

**Issue by mweibel** [candy-chat/candy#400]
Hi all

As you might have seen, i released a new candy version today. Candy as well as candy-plugins have been merged into master. Tbh i didn't test much and that's why i'm opening this discussion. 
Neither me nor @pstadler have contributed significant changes in the past year or so. We have been busy with work and free time and aren't using XMPP that much anymore to maintain an awesome software project as candy is. 

I propose to give the lead of the project to anyone who's willing to step in. I'd remove the dev branch and just commit to master / make prs to master. 

I'd propose to give the lead to @benlangfeld, @melissanoelle and @bklang. 

What's your opinion?

**Comment by pstadler** [comment]
I'm in favor of that. It's also a good time to decide over project goals.

**Comment by kripton** [comment]
I completely agree with not needing a dev-Branch. About leader/maintainership I cannot comment since I'm too new to this project.

**Comment by benlangfeld** [comment]
I would be happy to take on maintainership of Candy; it fits with the suite of other projects which I maintain. I doubt @bklang will want to be directly involved at this level. I am not sure if @melissanoelle is still using Candy or XMPP in any capacity.

In fact, the [Adhearsion Foundation](http://www.adhearsion.com/foundation) would be happy to accept Candy as a member project in order to ensure its long-term sustainability if this is something that interests you.

As for versioning, it does seem pragmatic to cease assigning version numbers to Candy and to avoid promises of backward compatibility until such point as we are more firmly decided on a resting point for the API and the direction of the project overall, which I think should be discussed formally.

**Comment by mweibel** [comment]
Ok. Adhearsion Foundation sounds good to me, what would be the steps involved to move it there? :)

**Comment by pstadler** [comment]
@benlangfeld sounds good!

@mweibel how about the demo? Currently http://www.swissjabber.ch/ is hosting a public XMPP room on their server while the client is hosted on your domain, is this correct?

In the past we had an issue where the demo stopped every now and then and we had to ask our contact at nine.ch for bringing it back up. We should inform them about the changes as soon as a decision is made whether we'd like to continue to use their server or not and make an short introduction probably.

I suggest to move the client to another place as well.

**Comment by melissanoelle** [comment]
I am not currently using Candy or XMPP. I'm not sure that I'm interested in maintaining anything on Candy Core at the moment, to be honest. In a perfect world where time is more plentiful, I'd be interested in changing over the Candy front-end to React or some such and _maybe_ looking at detangling Candy Core from a front-end Candy client (or at least simplifying it), but it's likely not going to happen given my current priorities. 

I am not sure that given my current goals and time commitments that it even makes sense for me to be included on this team because I don't plan on actively developing on Candy right now.

Moving this project to the Adhearsion Foundation probably makes a lot of sense for this project, as they're both concerned with communication and this project could be a good complement to that. Also, all of the members of AF are pretty vocal/active in their respective communities and it would help get this project some face time.

And I would also fully support @benlangfeld taking ownership of this project.

**Comment by tylermauthe** [comment]
Great to see it moving to a Foundation, I just selected Candy for a project and would hate to see it languish.

+1 on improvements to front-end, moving towards something closer to a Web Component. I'd be interested in assisting with this if there were other people interested...

**Comment by mweibel** [comment]
> I'd be interested in changing over the Candy front-end to React or some such and maybe looking at detangling Candy Core from a front-end Candy client (or at least simplifying it), but it's likely not going to happen given my current priorities. 

absolutely, this is in my opinion also the way to go. 

@tylermauthe welcome ;) and please feel free to get involved in contributing!

**Comment by benlangfeld** [comment]
@tylermauthe I'd love to hear your thoughts on the technical future of Candy. I will post my own at the weekend.

@pstadler What is nine.ch used for? If swissjabber.ch is happy to continue hosting the XMPP server, and the demo client is hosted on Github Sites, then I think were good.

@mweibel In order for Candy to become a member project of the Adhearsion Foundation, it would simply require that control of the project (ownership of the Github organisation, in this case) be provided to a member of the board of the foundation (me is fine) and that all past (significant) contributors sign a copyright assignment, assigning their copyright in contributions to the project to the Foundation such that the Foundation may assert copyright over the whole codebase. I will organise this assuming you and @pstadler agree in principle. Optionally, the candidate member project may move its repositories to the [Adhearsion organisation](https://github.com/adhearsion) on Github but that is by no means necessary.

**Comment by pstadler** [comment]
@benlangfeld swissjabber is a service provided by nine.ch. The demo client probably can't be hosted on GitHub because of the missing ability to proxy requests.

Regarding copyrights / ownership: as long as Candy is released under MIT or a similar permissive license this is not a problem. I'd like to keep the repositories in the current organization and stay a public member if this is possible.

Glad that everybody seems to be on the same page :+1:

**Comment by benlangfeld** [comment]
@pstadler Where is the demo currently hosted? If it would be more convenient, @MojoLingo would be happy to sponsor the demo entirely without dependence on swissjabber/nine.ch.

The Adhearsion Foundation is committed to permissive licensing. Most (if not all) of its other projects are licensed MIT (indeed it was created partly for the purpose of smoothly [relicensing Adhearsion itself](https://github.com/adhearsion/adhearsion/commit/5716546eaddbc70cd61bc57e88a4a0e534f5eb52) from LGPL to MIT) and this pattern would of course apply to Candy.

As for retaining the current organisation and all current committers retaining commit access, this is absolutely not a problem.

**Comment by mweibel** [comment]
@benlangfeld 
Demo is currently hosted on my own server (iframe pointing to http://dev.openflex.net/candy/). You're welcome to move this to MojoLingo. AFAIR the BOSH endpoint is whitelisted by IP address, so once you move the demo, the BOSH endpoint won't be working anymore (not sure though, could be that they changed that in the meantime). 

regarding copyright assignment: For me it's no problem to assign copyright to the foundation (wouldn't mind an honorable mention though :P) but as we initially developed Candy within the Amiado Group AG, we agreed to keep their copyright statement for the year mentioned in the statement. I suppose this needs to stay (no one I know is working there anymore so I don't think we could get out of that).

**Comment by benlangfeld** [comment]
That's no problem, the statement of their copyright in 2011 and then yours onwards is a valid assignment and we'll do the same this time.

Lets deal with copyright and admin on the candy org first, then I'll get a new demo server setup if you'd prefer to shut yours down.

**Comment by benlangfeld** [comment]
Tagging also @candy-chat/candy-plugins-contributors and @Sudrien, @bklang, @strix-technica, @macedo, @Flet, @davidvandertuijn, @bobek, @PaulSD, @vitalyster, @jdcaruso, @naro, @joshuah, @melissanoelle, @lkraav, @kripton, @linkmauve, @indeyets, @insertjokehere, @ser, @jfefe, @kyriog, @smerrill, @MOZGIII, @eluzgin, @aadityabhatia who have variously contributed to Candy in the past. This serves as notice that [Adhearsion Foundation Inc](http://adhearsion.com/foundation), a Florida 501(c)(3) Not For Profit Corporation intends to assert copyright over the Candy project and its various contributions starting Aug 1st 2015 for the purpose of ensuring the long-term vitality of the project and defending the project from third-party copyright claims.

Other than myself, @mweibel and @pstadler whose contributions individually represent more than 5% of the LoC of the Candy project, you do not need to take any action if you agree with this assignment of copyright in your contributions. If you have objections or concerns, please contact me either on this thread or directly (blangfeld@adhearsion.com) and I will be happy to clear those up. In the case that we cannot agree to an assignment in copyright, an alternative contribution will be made to remove any disputed contribution from the project and therefore the assignment.

@mweibel and @pstadler If you could complete and send me the attached assignment doc, that completes the first step of moving the project to the foundation.

[CandyCopyrightAssignment.pdf](https://github.com/candy-chat/candy/files/704/CandyCopyrightAssignment.pdf)

**Comment by MOZGIII** [comment]
Good stuff :+1:

**Comment by maennchen** [comment]
@benlangfeld: Does this issue also apply to the candy-plugin repository? If yes, you also got my :+1:

**Comment by macedo** [comment]
Good!! you got my :+1:

**Comment by benlangfeld** [comment]
Yes it does, @maennchen, though copyright in plugins will be assigned individually. Any plugins where the author does not respond or objects will be proposed for removal from candy-plugins.

**Comment by Sudrien** [comment]
No objections - would it be preferred if I include an MIT-style license with my plugins, or is it safe to assume those would fall under the main license?

**Comment by insertjokehere** [comment]
No objections here

**Comment by troymccabe** [comment]
:+1:

**Comment by benlangfeld** [comment]
They will fall under the main MIT license of the candy-plugins repo.

**Comment by bobek** [comment]
:+1:

**Comment by melissanoelle** [comment]
:+1:

**Comment by bklang** [comment]
:+1:

**Comment by mweibel** [comment]
Awesome to see everyone chiming in :)

@benlangfeld you should now be owner of the Candy organization on Github, as well as I sent you my signed Copyright assignment.

**Comment by maennchen** [comment]
@benlangfeld: Do I need to sign a Copyright assignment too for the plugins?

**Comment by ddevlin** [comment]
:+1:

**Comment by ddevlin** [comment]
The [timeago plugin](https://github.com/candy-chat/candy-plugins/tree/master/timeago) I contributed contains an (outdated) inline copy of @rmm5t's [jquery-timeago](https://github.com/rmm5t/jquery-timeago). jquery-timeago is MIT licensed and I preserved the original copyright notice: https://github.com/candy-chat/candy-plugins/blob/master/timeago/candy.js#L46

In those pre-Bower days this seemed like the easier option (rather than getting users to download jquery-timeago separately). @benlangfeld I'd be happy to refactor if you have a preferred way of handling that dependency.

**Comment by benlangfeld** [comment]
@mweibel: Thank you. I did receive your assignment. I'm now only waiting for @pstadler's and we're good.

@maennchen: Taking a look again at candy-plugins, you are indeed correct that I need assignments from you, @melissanoelle and @troymccabe. Would you guys please send me a completed assignment?

```
➭ git fame
Blame:         100% |ooooooooooooooooooooooooooooooooooooooooo| Time:   0:00:01

Total number of files: 119
Total number of lines: 6,478
Total number of commits: 263
+---------------------+-------+---------+-------+--------------------+
| name                | loc   | commits | files | distribution       |
+---------------------+-------+---------+-------+--------------------+
| Melissa Noelle      | 2,185 | 32      | 22    | 33.7 / 12.2 / 18.5 |
| Michael Weibel      | 1,832 | 69      | 32    | 28.3 / 26.2 / 26.9 |
| Jonatan Männchen   | 353   | 23      | 10    | 5.4 / 8.7 / 8.4    |
| troymccabe          | 333   | 17      | 14    | 5.1 / 6.5 / 11.8   |
| Patrick Stadler     | 304   | 36      | 13    | 4.7 / 13.7 / 10.9  |
| Troy McCabe         | 301   | 7       | 8     | 4.6 / 2.7 / 6.7    |
| Ben Klang           | 298   | 14      | 4     | 4.6 / 5.3 / 3.4    |
| David Devlin        | 194   | 1       | 3     | 3.0 / 0.4 / 2.5    |
| Patrick Forget      | 155   | 4       | 3     | 2.4 / 1.5 / 2.5    |
| David van der Tuijn | 125   | 2       | 2     | 1.9 / 0.8 / 1.7    |
| Sudrien             | 114   | 3       | 3     | 1.8 / 1.1 / 2.5    |
| Ben Langfeld        | 110   | 3       | 4     | 1.7 / 1.1 / 3.4    |
| warcode             | 46    | 9       | 3     | 0.7 / 3.4 / 2.5    |
| Drew Harry          | 40    | 15      | 6     | 0.6 / 5.7 / 5.0    |
| Manuel Alabor       | 29    | 1       | 3     | 0.4 / 0.4 / 2.5    |
| Jonatan Männchen    | 18    | 7       | 2     | 0.3 / 2.7 / 1.7    |
| Leho Kraav          | 16    | 4       | 2     | 0.2 / 1.5 / 1.7    |
| Paul Donohue        | 8     | 1       | 2     | 0.1 / 0.4 / 1.7    |
| Not Committed Yet   | 7     | 0       | 0     | 0.1 / 0.0 / 0.0    |
| Iain J. Watson      | 4     | 3       | 1     | 0.1 / 1.1 / 0.8    |
| Johan Oudinet       | 3     | 1       | 1     | 0.0 / 0.4 / 0.8    |
| alexandre melard    | 1     | 1       | 1     | 0.0 / 0.4 / 0.8    |
| Eren Türkay         | 1     | 1       | 1     | 0.0 / 0.4 / 0.8    |
| Joshua Heiks        | 1     | 1       | 1     | 0.0 / 0.4 / 0.8    |
| Alexey Zakhlestin   | 0     | 1       | 0     | 0.0 / 0.4 / 0.0    |
| Eugene Luzgin       | 0     | 3       | 0     | 0.0 / 1.1 / 0.0    |
| Mel Adamei          | 0     | 2       | 0     | 0.0 / 0.8 / 0.0    |
| hep                 | 0     | 2       | 0     | 0.0 / 0.8 / 0.0    |
+---------------------+-------+---------+-------+--------------------+
28 rows in set
```

@ddevlin: Initially I will just leave that as it is and it will not cause a problem. If you wanted to move it to being a [Bower dependency](https://github.com/candy-chat/candy-plugins/blob/master/bower.json#L30) then that would be great!

**Comment by maennchen** [comment]
@benlangfeld: I sent you the assignment.

**Comment by benlangfeld** [comment]
@maennchen I don't think I actually received that. Which email address did you send it to?

I've now received assignments from @mweibel and @pstadler so we'll be announcing the transition to the Adhearsion Foundation later this week.

**Comment by maennchen** [comment]
@benlangfeld I sent it to ben@langfeld.me.

Do you still use your PGP Key with the Fingerprint "181D 7230 C198 2F01 D975  1710 F0C0 7D7B 2AC4 F268"?

**Comment by benlangfeld** [comment]
> Do you still use your PGP Key with the Fingerprint "181D 7230 C198 2F01 D975 1710 F0C0 7D7B 2AC4 F268"?

I do.

I found your email; it had been sent to spam by gmail.

**Comment by maennchen** [comment]
Gmail doesn't like PGP at all. It throws even internal emails in the Google Apps into the Spam if they're encrypted -.-

**Comment by mweibel** [comment]
@benlangfeld will transfer ownership of the google group as well as the google analytics account as well now ;)

**Comment by PaulSD** [comment]
:+1:
