### ISSUE TITLE
Multiple session connections always kick each other

### ISSUE THREAD

**Issue by gburgwardt** [candy-chat/candy#407]
Hello-

I've got a working setup of candy-chat, and am trying to implement it such that on my site, users will have likely have many different tabs open, each one having its own candy instance. Those instances need to cooperate and not kick each other off the network. The XMPP server allows this, I've verified with other chat clients, but candy always kicks other candy instances off.

Any advice?

**Comment by benlangfeld** [comment]
How are you authenticating users? Are you always logging them in with the same resource? If you want multiple sessions with the same bare JID then you need to assign each a different resource.

**Comment by gburgwardt** [comment]
Wow, awesome response time :)

I'm using the example code, but I've added ```Candy.about.name = "9801";``` above ```Candy.Core.connect();``` as suggested in some conversation somewhere I can't find right now. 9801 is just a random number, and I have a second page that is the same but about.name is set to "aaaa", I assumed that would be different enough.

**Comment by tylermauthe** [comment]
When you connect to an XMPP server, you provide a username, nickname and resource.

Connections are mutually exlusive based on username + resource. Users can log in many times with the same username and nickname as long as the resource provided is different.

For example:

```javascript
var theNickname = "David Hasselhoff";
Candy.init("/chat-server/", {
	core: {
		resource: theNickname + (new Date()).getTime() // adds a unique timestamp to nickname
	}
});
```

**Comment by gburgwardt** [comment]
Tried implementing what you showed in your example, but I'm getting 
```[Strophe][ERROR]: request id 5.5 error 502 happened
Candy.Core</a.init/b.log()candy.min.js (line 1)
h.error()libs.min.js (line 1)
a.Bosh.prototype._onRequestStateChange()```

Probably not a candy bug and I apologize, but I'm not sure where else to find an answer.

And yes I did replace chat-server to fit my server.

**Comment by tylermauthe** [comment]
502 is an HTTP status code that indicates you probably didn't set the chat-server correctly.

Since this isn't a bug in Candy, do you mind taking your support request to the [Mailing List](http://groups.google.com/group/candy-chat)?
