### ISSUE TITLE
Example index.html wrong.

### ISSUE THREAD

**Issue by oxivanisher** [candy-chat/candy#411]
Hi There

I believe the example/index.html is not correct for version 2.0.

Greeting, oxi

**Comment by mweibel** [comment]
Could you explain what you mean with not correct? ;)

**Comment by oxivanisher** [comment]
Sure :)

Currently in [example/index.html](../blob/master/example/index.html):
```html
	<script type="text/javascript" src="../libs.min.js"></script>
	<script type="text/javascript" src="../candy.min.js"></script>
```
But:
* The source is now in the [src/](../tree/master/src) dir
* There is no candy.min.js just a candy.js
* There is no libs*.js file anymore

After just checking out the current commit, fixing the filename, removing the lib import did not work, i rolled back to my backup. ;)

**Comment by mweibel** [comment]
Did you download the .zip from the repository itself or "candy-2.0.0.zip" from https://github.com/candy-chat/candy/releases/tag/v2.0.0 ?

**Comment by oxivanisher** [comment]
No ... and this was the problem for my installation. Successfully updated to V2.0. :)
So i can delete my git checkouts? Do i have to use the ZIPs for the future?
If you answer me this, the issue is closed. :+1:

**Comment by mweibel** [comment]
yep you can delete them. If you want to use the git repo directly you'd need to build the bundle yourself (by running grunt, which you need to install first using npm, which you need to install first by installing nodejs... ;))
