### ISSUE TITLE
Wrong code in Candy/src/core/action.js file

### ISSUE THREAD

**Issue by OpenSiteMobile** [candy-chat/candy#413]
Hi all,

I came across this in the Candy/src/core/action.js file (from commit cfc83b56420bb4935bd1b7980f7090962b0e62f5). The code from the Jabber.Roster sections look like this:

```
		Roster: function() {
			var roster = Candy.Core.getConnection().roster,
				options = Candy.Core.getOptions();
			roster.registerCallback(Candy.Core.Event.Jabber.RosterPush);
			$.each(options.initialRosterItems, function (i, item) {
				// Blank out resources because their cached value is not relevant
				item.resources = {};
			});
			roster.get(
				Candy.Core.Event.Jabber.RosterFetch,
				options.initialRosterVersion,
				options.initialRosterItems
			);
			// Bootstrap our roster with cached items
			Candy.Core.Event.Jabber.RosterLoad(roster.items);
		},
```

When (I'm guessing) it should look like more like this:
```
        Roster: function() {
            Candy.Core.getConnection().sendIQ($iq({
                type: "get",
                xmlns: b.NS.CLIENT
            }).c("query", {
                xmlns: b.NS.ROSTER
            }).tree())
        },
```
It looks like someone's development stuff got into the current master commit. I could find no "Candy.Core.getConnection().roster.registerCallback" or "Candy.Core.getConnection().roster.get" functions to go along with this v2.0.0 code, so I'm guessing it lies somewhere else, not included yet in the new release.

**Comment by mweibel** [comment]
From where did you download the code? Roster is from strophejs-plugins which is installed using bower but the proper zip file on the release page should contain all the things already built and ready to use.

**Comment by benlangfeld** [comment]
> It looks like someone's development stuff got into the current master commit.

Nope, not at all. If you just checked out the git repository then you'll need to build according to the documentation in https://github.com/candy-chat/candy/blob/master/CONTRIBUTING.md.

**Comment by OpenSiteMobile** [comment]
Sorry about that. I didn't see the Roster plugin that was added. I'm from the old days, when we just loaded the new/updated files ourselves ;)

I personally don't like bower, but understand the need you all have for keeping everything in sync. Thanks for the reply.

**Comment by OpenSiteMobile** [comment]
I'm curious? Why so far back on the Strophe version? bower.js file calls for strophe v1.1.3. Unless I'm looking at the wrong GitHub Strophe files, version 1.2.2 is the latest.

**Comment by benlangfeld** [comment]
Strophe switched to AMD which broke our test suite.

**Comment by OpenSiteMobile** [comment]
I'm also curious about the RosterLoad function? Is there a reason that this is done each time Candy.Core.Action.Jabber.Roster is called?
```
// Bootstrap our roster with cached items
Candy.Core.Event.Jabber.RosterLoad(roster.items);
```
It looks like it gets the stuff from the first or previous Strophe connection? Is it important to track the differential values or something?

**Comment by benlangfeld** [comment]
This is called roster versioning and is to avoid having to download the entire roster on every page load.

**Comment by OpenSiteMobile** [comment]
Awesome. Thanks for the reply.
