### ISSUE TITLE
Plugin roomPanel

### ISSUE THREAD

**Issue by konradsztukowski** [candy-chat/candy#421]
I use OpenFire for CandyChat on my website and i have one conference service in openfire and 3 rooms, but only the first created room is used and visible, so i want to use the roomPanel plugin but I don't understand how to use it. I used te script and the css file but how and where do i call the init method where do I have to put code and how should it look like? I quess that in the JS file i need to specify the rooms names and jids but how to initiate the plugin?

**Comment by benlangfeld** [comment]
You call init after initializing Candy. The docs are very clear at https://github.com/candy-chat/candy-plugins/tree/master/roomPanel.
