### ISSUE TITLE
Connection keeps dissconnecting, How to edit index.html

### ISSUE THREAD

**Issue by sriducati** [candy-chat/candy#423]
Hello All,

I admit Candy Chat is good but it keeps disconnecting, There is nothing we can about it I almost tried all solutions listed here and also in google groups,Well but I think i found a better solution though stack,which can fix this problem,,, well it is by sending `presence` event every `10 seconds using setTimeInterval` how can we implement this?? which file can i edit? could anyone please show with a code example?

**Comment by benlangfeld** [comment]
You can do this in your own code, perhaps setting up the timer in a callback on connection: https://candy-chat.github.io/candy/docs/files/view/observer-js.html#candy:view.connection.status-STROPHE-STATUS. I don't think there's a case for this to be in core.
