### ISSUE TITLE
[Request] Util.Linkify the urls in the HTML version

### ISSUE THREAD

**Issue by anoland** [candy-chat/candy#434]
I'm having a problem with the linkify function when html anchor tags aready exist.

https://groups.google.com/forum/#!topic/candy-chat/BV1wUm-T4MU

As suggested, a feature request.

Thanks

**Comment by anoland** [comment]
@benlangfeld,
What is involved in getting this feature added? I'm afraid I've never set up an environment to re-bundle scripts.

Thanks,
Adrian

**Comment by benlangfeld** [comment]
@anoland You'd need to follow the instructions in CONTRIBUTING.md to build Candy for yourself, clone the repository, figure out what change you want to make, make & test it, and then submit a pull request.
