### ISSUE TITLE
Anyone please reply.....Trying to make responsive design but Template.js not allowing 

### ISSUE THREAD

**Issue by sriducati** [candy-chat/candy#435]
I am trying to change template.js ...but i dont know where the objects  are defined...

example 1:
	self.Room = {
		pane: '<div class="room-pane roomtype-{{roomType}}" id="chat-room-{{roomId}}"> {{>self.Message.item}}</div>' };

example 2:
	self.Message = {
		item: '<div>{{time}}</div>'};

As you can see Iam trying to call `>self.Message.item` inside `self.Room` but I am getting an error objects not found ....how do we successfully call in this way?

**Comment by benlangfeld** [comment]
You should grep for the name of the template. For example, https://github.com/candy-chat/candy/blob/master/src/view/pane/chat.js#L241. I think you are misunderstanding how Mustache works; perhaps you can explain what you're trying to achieve.

**Comment by humitos** [comment]
It would be amazing if you can make Candy responsive ;)
