### ISSUE TITLE
CandyJS Shows connecting only.

### ISSUE THREAD

**Issue by abhiit89** [candy-chat/candy#440]
I am trying to connect the candyjs to openfire server.
Openfire is working as i am using spark with it,
I have modified .htaccess file and put it inside example folder alongwith index.html file.
this is the content of my .htaccess file

AddDefaultCharset UTF-8
Options +MultiViews
RewriteEngine On
RewriteRule http-bind/ http://localhost:5280/http-bind/ [P]

and this is the console output is given below,

[Strophe][DEBUG]: _throttledRequestHandler called with 1 requests
candy.bundle.js:234 [Strophe][DEBUG]: request id 1.0 posting
candy.bundle.js:234 [Strophe][DEBUG]: request id 1.0 state changed to 1
candy.bundle.js:202 SENT: <body rid='3623918380' xmlns='http://jabber.org/protocol/httpbind' to='example.com ' xml:lang='en' wait='60' hold='1' content='text/xml; charset=utf-8' ver='1.6' xmpp:version='1.0' xmlns:xmpp='urn:xmpp:xbosh'/>
libs.min.js:2 POST http://example.com:5280/http-bind/ net::ERR_CONNECTION_TIMED_OUTk @ libs.min.js:2Strophe.Bosh._processRequest @ libs.min.js:2Strophe.Bosh._throttledRequestHandler @ libs.min.js:2Strophe.Bosh._connect @ libs.min.js:2f.Connection.connect @ libs.min.js:1a.connect @ libs.min.js:2a.connect @ candy.bundle.js:312(anonymous function) @ candy.bundle.js:4167x.event.dispatch @ jquery.min.js:5v.handle @ jquery.min.js:5
candy.bundle.js:234 [Strophe][DEBUG]: request id 1.1 state changed to 4
candy.bundle.js:234 [Strophe][ERROR]: request id 1.1 error 0 happenedk.debug.b.log @ candy.bundle.js:234f.error @ libs.min.js:1Strophe.Bosh._onRequestStateChange @ libs.min.js:2
candy.bundle.js:234 [Strophe][WARN]: request errored, status: 0, number of errors: NaN
candy.bundle.js:234 [Strophe][DEBUG]: _throttledRequestHandler called with 1 requests
candy.bundle.js:234 [Strophe][DEBUG]: request id 2.1 posting
candy.bundle.js:234 [Strophe][DEBUG]: request id 2.1 state changed to 1
candy.bundle.js:202 SENT: <body rid='3623918380' xmlns='http://jabber.org/protocol/httpbind' to='example.com ' xml:lang='en' wait='60' hold='1' content='text/xml; charset=utf-8' ver='1.6' xmpp:version='1.0' xmlns:xmpp='urn:xmpp:xbosh'/>

Please let me know what i am doing wrong.

**Comment by benlangfeld** [comment]
You should check your Apache and Openfire logs and try using telnet to confirm both are listening on the correct ports.

I also note that you have set Candy to connect directly to Openfire, making your Apache proxy useless.
