### ISSUE TITLE
Disconnect Called. BOSH module not started

### ISSUE THREAD

**Issue by scuba323** [candy-chat/candy#452]
I am trying to get Candy to work with my Ejabberd instance. I would like to use SSL for all connections. So when I try to get Candy to connect over TLS, I get this error;

[Paste of deugging](https://scuba323.com/url/SDVlc)

Also if it helps this is the section of my Apache config. I got it from a random Google search awhile back.

[Apache Config](https://scuba323.com/url/5SFP4)

**Comment by benlangfeld** [comment]
ejabberd doesn't have mod_bosh loaded. Check your ejabberd configuration :)
