### ISSUE TITLE
setup.sh does not work

### ISSUE THREAD

**Issue by sww314** [candy-chat/candy#456]
Running the setup.sh fails. Install log is attached as a zip file. 

[install.zip](https://github.com/candy-chat/candy/files/96953/install.zip)
> ./setup.sh 

Welcome to the Candy Vagrant setup

This script will setup a Vagrant box with development dependencies on it.
It will also build Candy and run tests to verify that everything is working.

In case of an error, use 'install.log' for log informations.

* Booting Vagrant box (this might take a while)...done
* Provisioning Vagrant box (this might take a few minutes)...
done
* Building Candy and running tests...
grunt-cli: The grunt command line interface. (v0.1.13)

Fatal error: Unable to find local grunt.

If you're seeing this message, either a Gruntfile wasn't found or grunt
hasn't been installed locally to your project. For more information about
installing and configuring grunt, please see the Getting Started guide:

http://gruntjs.com/getting-started
Connection to 127.0.0.1 closed.

Candy is now running on http://localhost:8080

**Comment by mweibel** [comment]
What's in the install.log?
Also do you have a `node_modules/grunt` folder (relative to the candy root folder)?

**Comment by sww314** [comment]
The entire install.log is atttached as a zip to the original post. Here is a snippet that seems pertinent.

==> default: Setting up nodejs (0.10.37-1chl1~trusty1) ...
==> default: /usr/bin/grunt -> /usr/lib/node_modules/grunt-cli/bin/grunt
==> default: grunt-cli@0.1.13 /usr/lib/node_modules/grunt-cli
==> default: ├── resolve@0.3.1
==> default: ├── nopt@1.0.10 (abbrev@1.0.7)
==> default: └── findup-sync@0.1.3 (lodash@2.4.2, glob@3.2.11)
==> default: /usr/bin/bower -> /usr/lib/node_modules/bower/bin/bower
==> default: bower@1.7.2 /usr/lib/node_modules/bower
==> default: └── semver-utils@1.1.1
==> default: npm
==> default:
==> default: ERR!
==> default:  Error: Attempt to unlock grunt@^0.4.5, which hasn't been locked
==> default: npm
==> default:
==> default: ERR!
==> default:      at unlock (/usr/lib/node_modules/npm/lib/utils/locker.js:44:11)
==> default: npm
==> default:  ERR!     at cb (/usr/lib/node_modules/npm/lib/cache/add-named.js:32:5)

**Comment by mweibel** [comment]
what happens if you change 
https://github.com/candy-chat/candy/blob/master/devbox/provisioning.sh

the lines 47 & 48 to run with sudo?

**Comment by sww314** [comment]
Sorry. I forgot to mention I changed 47-48 to use sudo. It fails to run without those changes.
