### ISSUE TITLE
Please provided v2.2.0 with bundled libraries.

### ISSUE THREAD

**Issue by mxjeff** [candy-chat/candy#461]
Please provide a tarball "ready to use" as for v2.1.0.

It looks like v2.2.0 release is available as source only.

Cheers

**Comment by benlangfeld** [comment]
Done. Seems the upload failed when I cut the release.

**Comment by mxjeff** [comment]
Thanks for such a reactivity !

The link on http://candy-chat.github.io/candy seems to be outdated as well ;-)

Cheers

**Comment by benlangfeld** [comment]
Pull requests accepted ;) gh-pages branch

**Comment by mxjeff** [comment]
Here it is #462 please review.

Cheers

**Comment by mxjeff** [comment]
Here it is #463 
Cheers
