### ISSUE TITLE
candy still binding  on connection....

### ISSUE THREAD

**Issue by hamdijmii1992** [candy-chat/candy#470]
I use candy js with mongooseIM as an XMPP server.
I add a room to my server as following:
[{mod_muc, [
             {host, "conference.localhost"},
             {access, all},
             {access_create, muc_create}
            ]},](url)
I add this room to my index.html as following:
	[//   ['test@conference.example.com']
					//     -> array of rooms to join after connecting
					autojoin: ['conference.localhost']](url)

but when I try to connect I had this log under and the window still binding on "Connecting ..."

This is my log:

[[]([Init]](url) Debugging enabled
candy.bundle.js:202 [Connection] Connecting
candy.bundle.js:234 [Strophe][DEBUG]: _throttledRequestHandler called with 1 requests
candy.bundle.js:234 [Strophe][DEBUG]: request id 1.0 posting
candy.bundle.js:234 [Strophe][DEBUG]: request id 1.0 state changed to 1
candy.bundle.js:202 SENT: <body rid='1242080132' xmlns='http://jabber.org/protocol/httpbind' to='localhost' xml:lang='en' wait='60' hold='1' content='text/xml; charset=utf-8' ver='1.6' xmpp:version='1.0' xmlns:xmpp='urn:xmpp:xbosh'/>
candy.bundle.js:234 [Strophe][DEBUG]: request id 1.1 state changed to 2
candy.bundle.js:234 [Strophe][DEBUG]: request id 1.1 state changed to 3
candy.bundle.js:234 [Strophe][DEBUG]: request id 1.1 state changed to 4
candy.bundle.js:234 [Strophe][DEBUG]: removing request
candy.bundle.js:234 [Strophe][DEBUG]: _throttledRequestHandler called with 0 requests
candy.bundle.js:234 [Strophe][DEBUG]: request id 1 should now be removed
candy.bundle.js:234 [Strophe][DEBUG]: request id 1.1 got 200
candy.bundle.js:234 [Strophe][INFO]: _connect_cb was called
candy.bundle.js:202 RECV: <body xmlns='http://jabber.org/protocol/httpbind' xmlns:xmpp='urn:xmpp:xbosh' xmlns:stream='http://etherx.jabber.org/streams' wait='60' requests='2' hold='1' from='localhost' accept='deflate,gzip' sid='0347645b5470cac3f8efaa18166d7f56d12d4f36' xmpp:restartlogic='true' xmpp:version='1.0' inactivity='30' maxpause='120'><stream:features><mechanisms xmlns='urn:ietf:params:xml:ns:xmpp-sasl'><mechanism>X-OAUTH</mechanism><mechanism>DIGEST-MD5</mechanism><mechanism>SCRAM-SHA-1</mechanism><mechanism>PLAIN</mechanism></mechanisms><register xmlns='http://jabber.org/features/iq-register'/><sm xmlns='urn:xmpp:sm:3'/></stream:features></body>
candy.bundle.js:234 [Strophe][DEBUG]: _throttledRequestHandler called with 0 requests
candy.bundle.js:234 [Strophe][DEBUG]: request id 2.0 posting
candy.bundle.js:234 [Strophe][DEBUG]: request id 2.0 state changed to 1
candy.bundle.js:202 SENT: <body rid='1242080133' xmlns='http://jabber.org/protocol/httpbind' sid='0347645b5470cac3f8efaa18166d7f56d12d4f36'><auth xmlns='urn:ietf:params:xml:ns:xmpp-sasl' mechanism='SCRAM-SHA-1'>biwsbj1hZG1pbixyPWQ0MWQ4Y2Q5OGYwMGIyMDRlOTgwMDk5OGVjZjg0Mjdl</auth></body>
candy.bundle.js:234 [Strophe][DEBUG]: request id 2.1 state changed to 2
candy.bundle.js:234 [Strophe][DEBUG]: request id 2.1 state changed to 3
candy.bundle.js:234 [Strophe][DEBUG]: request id 2.1 state changed to 4
candy.bundle.js:234 [Strophe][DEBUG]: removing request
candy.bundle.js:234 [Strophe][DEBUG]: _throttledRequestHandler called with 0 requests
candy.bundle.js:234 [Strophe][DEBUG]: request id 2 should now be removed
candy.bundle.js:234 [Strophe][DEBUG]: request id 2.1 got 200
candy.bundle.js:234 [Strophe][INFO]: _dataRecv called
candy.bundle.js:202 RECV: <body xmlns='http://jabber.org/protocol/httpbind' sid='0347645b5470cac3f8efaa18166d7f56d12d4f36'><challenge xmlns='urn:ietf:params:xml:ns:xmpp-sasl'>cj1kNDFkOGNkOThmMDBiMjA0ZTk4MDA5OThlY2Y4NDI3ZTdwcXZLZ25weFdlSy9SdGp3V281aFE9PSxzPW9IR0xBM3hYY2ZpU2tjRWRwalNwUWc9PSxpPTQwOTY=</challenge></body>
candy.bundle.js:234 [Strophe][DEBUG]: _throttledRequestHandler called with 0 requests
candy.bundle.js:234 [Strophe][DEBUG]: request id 3.0 posting
candy.bundle.js:234 [Strophe][DEBUG]: request id 3.0 state changed to 1
candy.bundle.js:202 SENT: <body rid='1242080134' xmlns='http://jabber.org/protocol/httpbind' sid='0347645b5470cac3f8efaa18166d7f56d12d4f36'><response xmlns='urn:ietf:params:xml:ns:xmpp-sasl'>Yz1iaXdzLHI9ZDQxZDhjZDk4ZjAwYjIwNGU5ODAwOTk4ZWNmODQyN2U3cHF2S2ducHhXZUsvUnRqd1dvNWhRPT0scD1hdFNySGVSeWpVMGdFZUQwN0ozSWt6aWpLSE09</response></body>
candy.bundle.js:234 [Strophe][DEBUG]: request id 3.1 state changed to 2
candy.bundle.js:234 [Strophe][DEBUG]: request id 3.1 state changed to 3
candy.bundle.js:234 [Strophe][DEBUG]: request id 3.1 state changed to 4
candy.bundle.js:234 [Strophe][DEBUG]: removing request
candy.bundle.js:234 [Strophe][DEBUG]: _throttledRequestHandler called with 0 requests
candy.bundle.js:234 [Strophe][DEBUG]: request id 3 should now be removed
candy.bundle.js:234 [Strophe][DEBUG]: request id 3.1 got 200
candy.bundle.js:234 [Strophe][INFO]: _dataRecv called
candy.bundle.js:202 RECV: <body xmlns='http://jabber.org/protocol/httpbind' sid='0347645b5470cac3f8efaa18166d7f56d12d4f36'><success xmlns='urn:ietf:params:xml:ns:xmpp-sasl'>dj0xc2M2dzh6VHkvTjQ4WisrYVVmL05OazFHT3c9</success></body>
candy.bundle.js:234 [Strophe][INFO]: SASL authentication succeeded.
candy.bundle.js:234 [Strophe][DEBUG]: _throttledRequestHandler called with 0 requests
candy.bundle.js:234 [Strophe][DEBUG]: request id 4.0 posting
candy.bundle.js:234 [Strophe][DEBUG]: request id 4.0 state changed to 1
candy.bundle.js:202 SENT: <body rid='1242080135' xmlns='http://jabber.org/protocol/httpbind' sid='0347645b5470cac3f8efaa18166d7f56d12d4f36' to='localhost' xml:lang='en' xmpp:restart='true' xmlns:xmpp='urn:xmpp:xbosh'/>
candy.bundle.js:234 [Strophe][DEBUG]: request id 4.1 state changed to 2
candy.bundle.js:234 [Strophe][DEBUG]: request id 4.1 state changed to 3
candy.bundle.js:234 [Strophe][DEBUG]: request id 4.1 state changed to 4
candy.bundle.js:234 [Strophe][DEBUG]: removing request
candy.bundle.js:234 [Strophe][DEBUG]: _throttledRequestHandler called with 0 requests
candy.bundle.js:234 [Strophe][DEBUG]: request id 4 should now be removed
candy.bundle.js:234 [Strophe][DEBUG]: request id 4.1 got 200
candy.bundle.js:234 [Strophe][INFO]: _dataRecv called
candy.bundle.js:202 RECV: <body xmlns='http://jabber.org/protocol/httpbind' xmlns:xmpp='urn:xmpp:xbosh' xmlns:stream='http://etherx.jabber.org/streams' wait='60' requests='2' hold='1' from='localhost' accept='deflate,gzip' sid='0347645b5470cac3f8efaa18166d7f56d12d4f36' xmpp:restartlogic='true' xmpp:version='1.0' inactivity='30' maxpause='120'><stream:features><bind xmlns='urn:ietf:params:xml:ns:xmpp-bind'/><session xmlns='urn:ietf:params:xml:ns:xmpp-session'/><register xmlns='http://jabber.org/features/iq-register'/><sm xmlns='urn:xmpp:sm:3'/></stream:features></body>
candy.bundle.js:234 [Strophe][DEBUG]: _throttledRequestHandler called with 0 requests
candy.bundle.js:234 [Strophe][DEBUG]: request id 5.0 posting
candy.bundle.js:234 [Strophe][DEBUG]: request id 5.0 state changed to 1
candy.bundle.js:202 SENT: <body rid='1242080136' xmlns='http://jabber.org/protocol/httpbind' sid='0347645b5470cac3f8efaa18166d7f56d12d4f36'><iq type='set' id='_bind_auth_2' xmlns='jabber:client'><bind xmlns='urn:ietf:params:xml:ns:xmpp-bind'><resource>Candy</resource></bind></iq></body>
candy.bundle.js:234 [Strophe][DEBUG]: request id 5.1 state changed to 2
candy.bundle.js:234 [Strophe][DEBUG]: request id 5.1 state changed to 3
candy.bundle.js:234 [Strophe][DEBUG]: request id 5.1 state changed to 4
candy.bundle.js:234 [Strophe][DEBUG]: removing request
candy.bundle.js:234 [Strophe][DEBUG]: _throttledRequestHandler called with 0 requests
candy.bundle.js:234 [Strophe][DEBUG]: request id 5 should now be removed
candy.bundle.js:234 [Strophe][DEBUG]: request id 5.1 got 200
candy.bundle.js:234 [Strophe][INFO]: _dataRecv called
candy.bundle.js:202 RECV: <body xmlns='http://jabber.org/protocol/httpbind' sid='0347645b5470cac3f8efaa18166d7f56d12d4f36'><iq xmlns='jabber:client' id='_bind_auth_2' type='result'><bind xmlns='urn:ietf:params:xml:ns:xmpp-bind'><jid>admin@localhost/Candy</jid></bind></iq></body>
candy.bundle.js:234 [Strophe][DEBUG]: _throttledRequestHandler called with 0 requests
candy.bundle.js:234 [Strophe][DEBUG]: request id 6.0 posting
candy.bundle.js:234 [Strophe][DEBUG]: request id 6.0 state changed to 1
candy.bundle.js:202 SENT: <body rid='1242080137' xmlns='http://jabber.org/protocol/httpbind' sid='0347645b5470cac3f8efaa18166d7f56d12d4f36'><iq type='set' id='_session_auth_2' xmlns='jabber:client'><session xmlns='urn:ietf:params:xml:ns:xmpp-session'/></iq></body>
candy.bundle.js:234 [Strophe][DEBUG]: request id 6.1 state changed to 2
candy.bundle.js:234 [Strophe][DEBUG]: request id 6.1 state changed to 3
candy.bundle.js:234 [Strophe][DEBUG]: request id 6.1 state changed to 4
candy.bundle.js:234 [Strophe][DEBUG]: removing request
candy.bundle.js:234 [Strophe][DEBUG]: _throttledRequestHandler called with 0 requests
candy.bundle.js:234 [Strophe][DEBUG]: request id 6 should now be removed
candy.bundle.js:234 [Strophe][DEBUG]: request id 6.1 got 200
candy.bundle.js:234 [Strophe][INFO]: _dataRecv called
candy.bundle.js:202 RECV: <body xmlns='http://jabber.org/protocol/httpbind' sid='0347645b5470cac3f8efaa18166d7f56d12d4f36'><iq xmlns='jabber:client' type='result' id='_session_auth_2'><session xmlns='urn:ietf:params:xml:ns:xmpp-session'/></iq></body>
candy.bundle.js:202 [Connection] Connected
candy.bundle.js:202 [Connection] Attached
candy.bundle.js:234 [Strophe][DEBUG]: _throttledRequestHandler called with 0 requests
candy.bundle.js:234 [Strophe][DEBUG]: _throttledRequestHandler called with 0 requests
candy.bundle.js:234 [Strophe][ERROR]: User connection callback caused an exception: TypeError: Cannot read property 'replace' of nullk.debug.b.log @ candy.bundle.js:234error @ libs.min.js:1_changeConnectStatus @ libs.min.js:1_sasl_session_cb @ libs.min.js:1run @ libs.min.js:1(anonymous function) @ libs.min.js:1forEachChild @ libs.min.js:1_dataRecv @ libs.min.js:1_onRequestStateChange @ libs.min.js:2
candy.bundle.js:234 [Strophe][DEBUG]: request id 7.0 posting
candy.bundle.js:234 [Strophe][DEBUG]: request id 7.0 state changed to 1
candy.bundle.js:202 SENT: <body rid='1242080138' xmlns='http://jabber.org/protocol/httpbind' sid='0347645b5470cac3f8efaa18166d7f56d12d4f36'><iq type='get' id='1:roster' xmlns='jabber:client'><query xmlns='jabber:iq:roster'/></iq><iq type='set' xmlns='jabber:client' id='2:sendIQ'><enable xmlns='urn:xmpp:carbons:2'/></iq></body>
candy.bundle.js:234 [Strophe][DEBUG]: request id 7.1 state changed to 2
candy.bundle.js:234 [Strophe][DEBUG]: request id 7.1 state changed to 3
candy.bundle.js:234 [Strophe][DEBUG]: request id 7.1 state changed to 4
candy.bundle.js:234 [Strophe][DEBUG]: removing request
candy.bundle.js:234 [Strophe][DEBUG]: _throttledRequestHandler called with 0 requests
candy.bundle.js:234 [Strophe][DEBUG]: request id 7 should now be removed
candy.bundle.js:234 [Strophe][DEBUG]: request id 7.1 got 200
candy.bundle.js:234 [Strophe][INFO]: _dataRecv called
candy.bundle.js:202 RECV: <body xmlns='http://jabber.org/protocol/httpbind' sid='0347645b5470cac3f8efaa18166d7f56d12d4f36'><iq xmlns='jabber:client' from='admin@localhost' to='admin@localhost/Candy' id='1:roster' type='result'><query xmlns='jabber:iq:roster'/></iq></body>
candy.bundle.js:234 [Strophe][DEBUG]: _throttledRequestHandler called with 0 requests
candy.bundle.js:234 [Strophe][DEBUG]: request id 8.0 posting
candy.bundle.js:234 [Strophe][DEBUG]: request id 8.0 state changed to 1
candy.bundle.js:202 SENT: <body rid='1242080139' xmlns='http://jabber.org/protocol/httpbind' sid='0347645b5470cac3f8efaa18166d7f56d12d4f36'><presence id='pres:3' xmlns='jabber:client'><priority>1</priority><c xmlns='http://jabber.org/protocol/caps' hash='sha-1' node='https://candy-chat.github.io/candy/' ver='kR9jljQwQFoklIvoOmy/GAli0gA='/></presence></body>
candy.bundle.js:234 [Strophe][DEBUG]: request id 8.1 state changed to 2
candy.bundle.js:234 [Strophe][DEBUG]: request id 8.1 state changed to 3
candy.bundle.js:234 [Strophe][DEBUG]: request id 8.1 state changed to 4
candy.bundle.js:234 [Strophe][DEBUG]: removing request
candy.bundle.js:234 [Strophe][DEBUG]: _throttledRequestHandler called with 0 requests
candy.bundle.js:234 [Strophe][DEBUG]: request id 8 should now be removed
candy.bundle.js:234 [Strophe][DEBUG]: request id 8.1 got 200
candy.bundle.js:234 [Strophe][INFO]: _dataRecv called
candy.bundle.js:202 RECV: <body xmlns='http://jabber.org/protocol/httpbind' sid='0347645b5470cac3f8efaa18166d7f56d12d4f36'><iq xmlns='jabber:client' from='admin@localhost' to='admin@localhost/Candy' id='2:sendIQ' type='result'/></body>
candy.bundle.js:234 [Strophe][INFO]: no requests during idle cycle, sending blank request
candy.bundle.js:234 [Strophe][DEBUG]: request id 9.0 posting
candy.bundle.js:234 [Strophe][DEBUG]: request id 9.0 state changed to 1
candy.bundle.js:202 SENT: <body rid='1242080140' xmlns='http://jabber.org/protocol/httpbind' sid='0347645b5470cac3f8efaa18166d7f56d12d4f36'/>
candy.bundle.js:234 [Strophe][DEBUG]: request id 9.1 state changed to 2
candy.bundle.js:234 [Strophe][DEBUG]: request id 9.1 state changed to 3
candy.bundle.js:234 [Strophe][DEBUG]: request id 9.1 state changed to 4
candy.bundle.js:234 [Strophe][DEBUG]: removing request
candy.bundle.js:234 [Strophe][DEBUG]: _throttledRequestHandler called with 0 requests
candy.bundle.js:234 [Strophe][DEBUG]: request id 9 should now be removed
candy.bundle.js:234 [Strophe][DEBUG]: request id 9.1 got 200
candy.bundle.js:234 [Strophe][INFO]: _dataRecv called
candy.bundle.js:202 RECV: <body xmlns='http://jabber.org/protocol/httpbind' sid='0347645b5470cac3f8efaa18166d7f56d12d4f36'><presence xmlns='jabber:client' from='admin@localhost/Candy' to='admin@localhost/Candy' xml:lang='en' id='pres:3'><priority>1</priority><c xmlns='http://jabber.org/protocol/caps' hash='sha-1' node='https://candy-chat.github.io/candy/' ver='kR9jljQwQFoklIvoOmy/GAli0gA='/></presence></body>
candy.bundle.js:202 [Jabber] Presence
candy.bundle.js:234 [Strophe][INFO]: no requests during idle cycle, sending blank request
candy.bundle.js:234 [Strophe][DEBUG]: request id 10.0 posting
candy.bundle.js:234 [Strophe][DEBUG]: request id 10.0 state changed to 1
candy.bundle.js:202 SENT: <body rid='1242080141' xmlns='http://jabber.org/protocol/httpbind' sid='0347645b5470cac3f8efaa18166d7f56d12d4f36'/>

Why my app still binding on Conncting ... and does not pass to other view ??

**Comment by hamdijmii1992** [comment]
I think that the source of bug is this error:
candy.bundle.js:234 [Strophe][ERROR]: User connection callback caused an exception: TypeError: Cannot read property 'replace' of nullk.debug.b.log @ candy.bundle.js:234error @ 
but I don't know how to fix it !!!

**Comment by mweibel** [comment]
This is a JID for a room with your config: `test@conference.localhost`
What you specified is: `conference.localhost`

You specified a wrong argument to autojoin. What you configured in the config is the muc host which is 
kind of like a domain for all MUC rooms. 
Then you set this host as the autojoin argument, when in fact you'd need to specify an actual room. So first create a room to autojoin and then in the config specify it as documented.

**Comment by hamdijmii1992** [comment]
@mweibel Thank you for this indication, but, I did not found the command line in mongooseIM that create a muc room !!!!
