### ISSUE TITLE
Mam supporting

### ISSUE THREAD

**Issue by hamdijmii1992** [candy-chat/candy#471]
Does candy js support  XEP-0313 (Message Archive Management) ??

**Comment by benlangfeld** [comment]
No, but we'd love to if someone was willing to implement it in a plugin.

**Comment by hamdijmii1992** [comment]
Sorry, Does strophe js support this module ??

**Comment by benlangfeld** [comment]
There is an out of date module for it at https://github.com/strophe/strophejs-plugins/tree/master/mam.

**Comment by hamdijmii1992** [comment]
@benlangfeld  I would implement such plugin to make candy support MAM, but I need to take some advices that make me on the correct path
