### ISSUE TITLE
"display status messages" always disabled.

### ISSUE THREAD

**Issue by pstadler** [candy-chat/candy#48]
As described here: http://groups.google.com/group/candy-chat/browse_thread/thread/9d9c7f89fd44c6aa

Candy.Util.deleteCookie() is broken.
Affected controls:
- Status messages
- Sound
- _Colors_ (plugin)

**Comment by bram1028** [comment]
This is still a problem in IE 11. The cookie is not being deleted.

**Comment by bram1028** [comment]
The `expires` format seems to be wrong. I changed it and it works now:

```
document.cookie = name + "=;expires=Thu, 01 Jan 1970 00:00:01 GMT;path=/";
```
