### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by SamGoody** [candy-chat/candy#490]
Am following the following steps:
(Note: bower, npm, and istanbul are installed globally).

1. git clone https://github.com/candy-chat/candy.git
2. cd candy
3. git checkout tags/v2.2.0
4. npm install
5. bower install
6. grunt

What happens:
```
Running "intern:unit" (intern) task
Listening on 0.0.0.0:9000
Starting tunnel...
Error: [POST http://localhost:4444/wd/hub/session] connect ECONNREFUSED 127.0.0.1:4444
Error: connect ECONNREFUSED 127.0.0.1:4444
  at Object.exports._errnoException  <util.js:870:11>
  at exports._exceptionWithHostPort  <util.js:893:20>
  at TCPConnectWrap.afterConnect [as oncomplete]  <net.js:1063:14>

>> TOTAL: tested 0 platforms, 0/0 tests failed; fatal error occurred
Warning: Error: [POST http://localhost:4444/wd/hub/session] connect ECONNREFUSED 127.0.0.1:4444
Error: connect ECONNREFUSED 127.0.0.1:4444
  at Object.exports._errnoException  <util.js:870:11>
  at exports._exceptionWithHostPort  <util.js:893:20>
  at TCPConnectWrap.afterConnect [as oncomplete]  <net.js:1063:14> Use --force to continue.

Aborted due to warnings.
```

Here is the whole output:
https://pastebin.ubuntu.com/23593269/

Have spent hours trying to install and fix depndencies, with no luck. Pretty please advise!

**Comment by benlangfeld** [comment]
Have you tried the master branch? If you want to use a release, why not download the release archive itself and skip the build step?

**Comment by mweibel** [comment]
probably just running `grunt build` would be enough. the default task of grunt runs the tests incl. functional tests which require some setup.

**Comment by SamGoody** [comment]
@mweibel That was all I needed, thanks. I am pretty new to grunt.  
However, for candy-plugins that didn't help: https://pastebin.ubuntu.com/23597554/
(Though for plugins I don't know that I need to run grunt at all.)  
Can you give a simple trick for that as well?  

@benlangfeld 
The issue has been solved, but before posting I tried the master and tagged branches.  
I asked on tagged only because it ought to be stable.  

However, even for releases, I prefer git to archive. 
It makes updates much easier to follow, and let's me see if of my own changes need to be modified in between updates. If not, that it merges all my changes silently.

Thank you all for the software, and for cheerfully putting up with noobs :)

**Comment by mweibel** [comment]
@SamGoody 
I think for plugins you can just git clone it and then reference the needed files separately, IIRC there's no build.. Grunt is only needed if you want to contribute.

That grunt there doesn't work is a separate issue and probably needs to be adressed separately.
