### ISSUE TITLE
Is this a dead project?

### ISSUE THREAD

**Issue by strypey** [candy-chat/candy#516]
I'm presuming from the long string of unanswered issues and the lack of commits to the code that this is a dead project? As such, I'm adding it to a list I of abandoned web-based chat software I maintain, in case the code is informative to active or new projects:
https://www.coactivate.org/projects/disintermedia/slacking-off/

If I am wrong, and Candy is still being actively maintained, please let me know.

**Comment by benlangfeld** [comment]
Yes

**Comment by strypey** [comment]
Thanks for the confirmation. Do you know whether any of the other
Adhearsion Foundation projects are still alive?

**Comment by strypey** [comment]
Thanks for the info @benlangfeld

**Comment by lkraav** [comment]
I've been considering moving to Mattermost for my private chat service platform.

There really doesn't seem to be a high level XMPP web ui available these days (I last did market research about 6 mo ago). Everything has weird UI/UX decisions or are dead as well.

**Comment by strypey** [comment]
@lkraav and anyone else interested,
I am curating a list of web-based chat apps that are free code software, with the primary goal of helping people find self-hostable, user-respecting replacements for Slack, and figure out wich ones is most suitable for their use case. Any additions, corrections, and other feedback is most welcome:
https://www.coactivate.org/projects/disintermedia/slacking-off/

For those particularly interested in federated systems, I encourage you to check out the Matrix federation protocol, which is a web-native alternative to XMPP, and potentially easier to write web clients for:
https://matrix.org/docs/guides/faq.html#what-is-the-difference-between-matrix-and-xmpp

**Comment by strypey** [comment]
@benlangfeld It might be helpful to add a prominent note at the top of the ReadMe file, so folks can see at a glance that this project is unmaintained.
